language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install -e .[test] pep8 coverage coveralls"

script:
  - nosetests --with-coverage --cover-package=webmock
  - pep8 webmock/__init__.py

after_success:
  - coveralls
